### ISSUE TITLE
[feature request] time option for "add image" with time lapse

### ISSUE THREAD

**Issue by julou** [ome/omero-figure#141]
It would be very useful to have a way to add one image several times (showing different frames, and aligned on a row / column) for time lapse datasets. A syntax like ID:start:end:by might do the job; one might want to distinguish between column and row alignement (using a different separator? or an optional argument? or give a matrix dimension?). 
Thinking about it, it might be easier to have dedicated dialog to select the frames and set the layout (in which case there would be a "add series" button next to the "add image" one). This could extended to handle any dimension of the dataset (channels, slice, time)…
Does this makes sense?

**Comment by will-moore** [comment]
Hi, thanks for the suggestion. I certainly have considered features such as those you're suggesting. However, the general philosophy of OMERO.figure is not to try and "hard code" the layout of figures. The predecessor of OMERO.figure was a collection of [figure scripts (still available)](http://help.openmicroscopy.org/publish.html#figures) for generating a split-view figure, time-lapse figure etc, but it seemed that every user wanted a different layout or style of figure. And the number of configuration options quickly got very large.
I have tried to make it very quick to copy & repetitively paste an image in OMERO.figure to duplicate it across the page, while clicking on the time > button to increment time for each image in turn. I believe this is a more flexible approach that doesn't require an additional features to design, document, learn, test etc.
 I hope this philosophy seems reasonable, and thanks for your interest in the project.

**Comment by julou** [comment]
Hi Will, it's understandable and I was indeed tuned by the flexibility of UX of omero.figure (congrats again!). Is there a script I can use if I want to arrange e.g. 50 different frames as a grid (without setting the time point manually)?

**Comment by will-moore** [comment]
You can use the "Movie Figure" script, which is currently only available in the Insight client. E.g. select 1 or more images (2 in this screenshot) and choose "Movie Figure" from the scripts menu:

![screen shot 2016-02-17 at 11 17 18](https://cloud.githubusercontent.com/assets/900055/13107977/495d5750-d568-11e5-9fb4-ccb3b984d539.png)

You can choose a bunch of options...

![screen shot 2016-02-17 at 11 15 33](https://cloud.githubusercontent.com/assets/900055/13107984/517283ca-d568-11e5-9fc5-c8d322e54cd0.png)

And it will create you a figure which is attached to one of the original images...

![screen shot 2016-02-17 at 11 16 29](https://cloud.githubusercontent.com/assets/900055/13108008/62f5e59c-d568-11e5-9820-1077f53a0ec9.png)

Hope that helps.

**Comment by julou** [comment]
it's good to know…
it would still be really nice in my opinion to have something similar in omero.figure. I completely understand from what you've already achieved that you will only consider solutions that are flexible enough to be useful to most… alright. I just hope something like that ends up on your list sooner than later! ;)

**Comment by will-moore** [comment]
Created a new trello card: https://trello.com/c/RJLukeeU/147-propagate-panels-across-z-t
Closing this issue....

**Comment by will-moore** [comment]
This PR allows you to script OMERO.figure layout in the browser dev-tools console, allowing you to create a "Movie figure": https://github.com/ome/omero-figure/pull/216
It should be in the next release of OMERO.figure.
