### ISSUE TITLE
OMERO Meeting Topics

### ISSUE THREAD

**Issue by jstitlow** [ome/omero-figure#155]
Hello, 

The Davis lab have been trialling OMERO figure and have come up with a list of comments / queries that I hope we can discuss at the meeting:
- can you use Gamma as well as max min with contrasting images in figure?
- can you “copy and paste” contrasting settings between images in figure or type in specific contrast values so different images get the same contrast?
- Could there be both max and average projection options for Z-stacks?
- As well as rotate could there also be flip (or mirror) horizontal and vertical?
- When you add images to a figure the most recent image can sit “on top” of another image as an overlay. Is there a way of doing this so you can get multiple image insertson figure independent of the order they were added (Layers)?
- Is there a way of adding arbitrarily placed characters e.g. N for nucleus the same way you can add an arrow anywhere, or even an arbitrary txt box - e.g. for making posters?
- Can you copy multiple image ID's at once from OMERO to paste into OMERO figure?

Many thanks

Josh

**Comment by will-moore** [comment]
To add multiple Image IDs at once, see the demo at https://youtu.be/8ZKAcowl4Tk?t=1m1s

**Comment by will-moore** [comment]
Thanks for your feedback and suggestions:
We have existing trello cards for a number of your feature requests:
 - 'Layers' request is covered  by https://trello.com/c/ECUiyEtJ/4-bring-to-front-send-to-back
 - Typing in contrast values card is https://trello.com/c/AozomHkL/125-sliders-allow-typing-in-values. 
 - Arbitrary characters https://trello.com/c/wtu7IVuN/10-stand-alone-labels

And I have created some new cards for others:
 - https://trello.com/c/mNvkTWpg/126-rendering-gamma-levels
 - https://trello.com/c/3LskKVSw/127-average-intensity-projection
 - https://trello.com/c/wlX18bfE/128-flip-vertical-or-horizontal

Look forward to discussing at the Dundee meeting next week

**Comment by will-moore** [comment]
@jstitlow A current workaround for "Bring to front" functionality is to copy and paste a panel, then delete the original. This will move a panel to the "top" layer.

**Comment by jstitlow** [comment]
Good idea, thanks.

*Josh Titlow, Ph.D.*
Postdoctoral Research Associate
Department of Biochemistry
University of Oxford, UK

South Parks Road
Oxford OX1 3QU, UK

(p) (44) (0) 1865 613272 (lab)
(w) http://joshtitlow.wordpress.com/

**Comment by will-moore** [comment]
Opened a PR allowing you to type in contrast values: https://github.com/ome/figure/pull/166

**Comment by will-moore** [comment]
Also created https://trello.com/c/FdxhWDPu/146-shape-text-label
Now all points covered by trello cards.... closing issue...
