### ISSUE TITLE
Italics for Labels

### ISSUE THREAD

**Issue by tjsamuels** [ome/omero-figure#157]
Hi,
I am trying to use Figure with some images of RNA FISH and need to be able to label the RNAs in italics on the images as this is the convention in Drosophila and other organisms. I can use Markdown to get italics in the Figure legend (as suggested on the Trello card) but I can't get it to work in the label. Is it also possible to get italics in the label itself or would these labels have to be added afterwards?
Thanks,
Tamsin (Davis Lab)

**Comment by will-moore** [comment]
Hi,
 You're right that markdown is not supported in Labels, although it has been requested already: see https://trello.com/c/BNjiEiAZ/46-labels-italics.
I'll add your request to that card and see when there's time to look into it.
Thanks for your feedback,
  Will.

**Comment by will-moore** [comment]
See trello card....
