### ISSUE TITLE
requirements vs Pillow

### ISSUE THREAD

**Issue by aleksandra-tarkowska** [ome/omero-figure#171]
Figure requirement `markdown` is installing latest Pillow, if that is done in the wrong order (that is likely as figure is installed after server installation) this will cause https://trello.com/c/jZjPZf8K/637-attributeerror-numpy-ndarray-object-has-no-attribute-tobytes.

**Comment by jburel** [comment]
Documentation has been changed. It is now recommended not to install using pip
