### ISSUE TITLE
Mirror images.

### ISSUE THREAD

**Issue by iandobbie** [ome/omero-figure#199]
Rotation is very nice but for consistency sometimes you need to mirror an image (eg to get all images in the same orientation). Can you add a mirror function, combined with rotation this allows all possible orientations.

**Comment by will-moore** [comment]
Thanks for the feedback. I've added it to a trello card at https://trello.com/c/wlX18bfE/128-flip-vertical-or-horizontal.

**Comment by will-moore** [comment]
Follow trello card. Closing issue...
