### ISSUE TITLE
Trouble installing omero_figure to web.apps (version 5.3.0-ice36-b59)

### ISSUE THREAD

**Issue by polkacode** [ome/omero-figure#237]
Hi,

I'm trying to install omero_figure on a server ( version 5.3.0-ice36-b59)
It already provides the OMERO.web front end just fine.

As the omero user I did the "pip install omero-figure", which worked,
but when I try to add the new application to the menus I get:

```
~$ bin/omero config append omero.web.apps '"omero_figure"'
Cannot retrieve default value for property omero.web.apps
```
I'm I missing something? 
Any help would be highly appreciated.

Thanks
Andreas

**Comment by will-moore** [comment]
You need to have your ```lib/python/omeroweb/``` on your ```$PYTHONPATH``` so that 
```from omeroweb import settings``` works.

**Comment by polkacode** [comment]
Hi Will,

thank you for your fast reply.
I'm sorry I think I'm confused now.

My OMERO installation lives in 
`/home/omero/OMERO.server
`
My omerowebenv lives in
`/home/omero/omerowebvenv
`
I installed the omero_figure module via the pip
binary in 
`/home/omero/omerowebvenv/bin/
`
So it got installed in 
`/home/omero/omerowebvenv/lib/python2.7/site-packages`

$PYTHONPATH was not set so far for the omero user, if I set it: 
`
export PYTHONPATH=/home/omero/OMERO.server/lib/python/omeroweb/`

I still get the same behaviour.

Cheers
Andreas

**Comment by manics** [comment]
Hi @polkacode

Could you paste the full commands you're running, including the commands you use to activate your virtualenv after you log in to the server?

**Comment by polkacode** [comment]
Hi guys,

thanks for your inputs. It turns out, I could resolve the issue, by re-checking 
my webclient's "runtime environment".
Omero Figure is running fine now.

Bests
Andreas

**Comment by jburel** [comment]
Glad to hear that you have everything working

Cheers
Jmarie
