### ISSUE TITLE
RFE: Modifier to restrict movement to X OR Y

### ISSUE THREAD

**Issue by dpwrussell** [ome/omero-figure#25]
It is very useful when working with something that should end up perfectly lined up to be able to move objects along one axis while locking the other.

For example, if I have four images in a square and wish to move the bottom two down a bit, it would be good to be able to hold down a modifier key while moving them so that they moved in the y axis only, x being locked.

**Comment by will-moore** [comment]
See https://trello.com/c/XYze2o7v/149-constrained-drag-n-drop
