### ISSUE TITLE
figure group permissions are not obvious

### ISSUE THREAD

**Issue by carandraug** [ome/omero-figure#284]
Figures belong to both a user and a group.  The first is pretty obvious and when searching for existing figures, one can filter by user.  However, figure group permissions are never referred on the GUI.  Since a user can belong to multiple groups, it's not obvious to the user which group his figures are.

The problem we just had were two users that belong to different primary groups and a same secondary group.  They wanted to share figures with images from this secondary group.  Because they were not aware of group permissions for figures, some of them ended up on their primary group and so were invisible to the other user.

The GUI should make some reference to the group a figure is in.  I would guess a 'Move to group' button on the 'File' menu may also be useful.

**Comment by carandraug** [comment]
See also related forum entry https://www.openmicroscopy.org/community/viewtopic.php?f=4&t=8485

**Comment by will-moore** [comment]
This is fixed by https://github.com/ome/omero-figure/pull/416.

**Comment by will-moore** [comment]
Fix was released today: https://github.com/ome/omero-figure/blob/master/CHANGELOG.md#440-february-2021
