### ISSUE TITLE
RFE: Layout Grid

### ISSUE THREAD

**Issue by dpwrussell** [ome/omero-figure#29]
An optional grid (think graph paper) that does not go into exported PDFs just to be used to align things.

Snap-to-grid drag-n-drop is also a coveted feature.

**Comment by will-moore** [comment]
Moved to trello:
https://trello.com/c/XYze2o7v/149-constrained-drag-n-drop
https://trello.com/c/rX8JMdZ0/150-grid-guidelines-overlay
