### ISSUE TITLE
No labels in channel sliders

### ISSUE THREAD

**Issue by thejohnhoffer** [ome/omero-figure#298]
Several people in our lab have let me know that it's difficult to visually correspond the channels in the `#channel_sliders` div with the channels in the main Webclient. They suggested adding named labels for each channel. @jaycopeland let me know that this has been discussed, but there are concerns over space-constraints. Here is the solution I've hacked together (in a very temporary way):

![screen shot 2018-06-15 at 3 55 24 pm](https://user-images.githubusercontent.com/9781588/41486962-8e61e688-70b4-11e8-8f84-6d6ce490788a.png)

The text is partially occluded depending on the position of the sliders, but that seems like a minor issue compared to the utility of this feature. @will-moore if this is an approach you'd like to take, I'd be interested in working towards implementing this in a proper pull request.

**Comment by will-moore** [comment]
I was proposing to adopt the same layout we use for the iviewer, to improve consistency between the apps (we've already been moving in this direction).

Screenshot below shows the same image in figure (left) and iviewer.

<img width="730" alt="screen shot 2018-06-17 at 21 40 45" src="https://user-images.githubusercontent.com/900055/41511878-451c1010-7277-11e8-908e-90dda1bac644.png">

As you can see, longer channel names are truncated. The question is whether you need to see more of the channel name to distinguish between them? The full channel names are shown with a tool-tip on the channel buttons.

If this works for you, it should be quite straight-forward to take the html/css from iviewer and apply to figure. If you'd like to help with this, that would be appreciated and I'm happy to give any pointers you may need.

**Comment by thejohnhoffer** [comment]
We're finding people in our lab also want some way to identify the "group" name for each channel. Often the channel labels are identical, but the channels belong to different groups. Here is a "DNA" label in a "T-cells" group as we're doing it now:
![untitled](https://user-images.githubusercontent.com/9781588/41613435-91cf5690-73c3-11e8-8e49-a73c8e289ea4.png)

To generate the image above, [we make](https://github.com/thejohnhoffer/ome_figure_hack/blob/master/hack.js#L81) a list of `{group, label}` from a combination of the `/pathviewer/viewer/<Image ID>/channelgroups` endpoint and the list of channels at `figureModel.panels.getSelected().at(0).get(channels)` each time a new image is selected. This a part of a [temporary solution](https://github.com/thejohnhoffer/ome_figure_hack/#installation) to get this working quickly.

If you're already including the full label in the button hovertext, what do you think about having the hovertext actually read something like `<full label> (<group>)`? And do you have a way to include channel groups directly in the `figureModel`?

**Comment by thejohnhoffer** [comment]
In general though I think that new style looks great. The labels probably logically belong on the buttons anyway, and I think usually the first 6 or so characters should be enough to quickly distinguish. And the hovertext is a great solution for providing the full name. I just wonder if you'd support including the channel group in that hovertext.

**Comment by will-moore** [comment]
I'm afraid I don't think the OME team can support the grouping of channels, since this feature is unique to Glencoe customers and we don't currently include PathViewer in any of our work.

**Comment by will-moore** [comment]
This was fixed in https://github.com/ome/omero-figure/pull/333
