### ISSUE TITLE
RFE: Pixel Measurements

### ISSUE THREAD

**Issue by dpwrussell** [ome/omero-figure#30]
Exact measurements for both formatting and display that show the pixel area represented by an image viewport. E.g. If I had 2 same sized viewports on the same image but one was much more zoomed in that the other, the pixel measurements on that one would be less.

**Comment by will-moore** [comment]
We now show the crop region of selected panels:
![screen shot 2017-04-27 at 11 41 04](https://cloud.githubusercontent.com/assets/900055/25479901/787023d8-2b3e-11e7-8287-50074eade120.png)

We also allow you to Copy the crop region (see above) and paste this as a new ROI on another panel:
![screen shot 2017-04-27 at 11 42 48](https://cloud.githubusercontent.com/assets/900055/25479970/be588e94-2b3e-11e7-93b2-fea377553a72.png)
