### ISSUE TITLE
Bug: Length of scale bar in exported PDF/TIFF

### ISSUE THREAD

**Issue by knabar** [ome/omero-figure#305]
Scale bars are displayed the correct length in the web UI, but in the exported file they are too long, apparently by a factor of `300/72`, i.e. there might be an extra or missing call to `scale_to_export_dpi`.

<img width="314" alt="screen shot 2018-07-09 at 13 56 25" src="https://user-images.githubusercontent.com/197099/42451669-38a840a2-8388-11e8-9144-5aefcca140af.png">

Left is web UI, right is exported file.

**Comment by sbesson** [comment]
Thanks @knabar. @will-moore is this the same bug than the one addressed in #304 ?

**Comment by will-moore** [comment]
Yes, looks like the same bug, assuming that's a big image @knabar?
Cheers.

**Comment by knabar** [comment]
@will-moore Yes, it is a big image, and my assumption that it was a fixed factor was wrong, so it does look like the bug from #304.  Thanks!
