### ISSUE TITLE
No ":" in default figure name

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-figure#314]
see:
 * https://github.com/ome/omero-figure/blob/6c1c258c96670265a53610dda62f832b2efb458c/src/js/models/figure_model.js#L421
 * https://twitter.com/totti0223/status/1055364434632171520

> i do not like to have colon included as a default file name candidate.  (regular expression things)

**Comment by will-moore** [comment]
Fixed in https://github.com/ome/omero-figure/pull/497
