### ISSUE TITLE
New workflow: inset handling

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-figure#319]
e.g. https://omero.lifesci.dundee.ac.uk/figure/file/364219

 * User adds a potentially ephemeral ROI to an image
 * Likely from the ROI edit dialog (since ROIs aren't clickable in the main UI) or potentially from the "Add labels" dialog, user chooses "Use as inset"
 * A new Image is created (optionally beside or below) cropped to the view window
 * Movement of the ROI updates the cropped view
 * Additionally, an option to "Draw connecting lines" is available to connect one appropriate top and bottom corner from the inset ROI to the cropped image

cc: @pwalczysko @jburel

**Comment by pwalczysko** [comment]
>User adds a potentially ephemeral ROI to an image
>Likely from the ROI edit dialog (since ROIs aren't clickable in the main UI) or potentially from the "Add labels" dialog, user chooses "Use as inset"

The two above points signal probably that the ROIs are too "well" hidden functionality, with some workflow caveats. This is also obvious when you try to add ROIs "from OMERO" from a long list.
I guess @jburel was suggesting a revisit of the ROI workflows.

>Movement of the ROI updates the cropped view

but, @joshmoore , as you said, the ROI cannot be moved or manipulated from the "main UI". This either means that the ROI workflow should be rehauled (see above) or you are looking at a laborious "jumping" between Edit ROI dialog (a specific dialog which edits only one image at a time atm) and the "main UI". This would in fact invalidate the workflow as suggested.

Or, somehow, we would have to introduce "ephemeral ROIs" which are editable from the main UI. Is that an easy thing to do ? In such case, why not to expand the "ephemeral ROIs" to be the "true Figure-ROIs" and ditch the clanky "ROI Edit" dialog (e.g. rehaul the ROI concepts in Figure, see above)

**Comment by pwalczysko** [comment]
@joshmoore Actually, partially, your workflow can be achieved in iviewer. 

   - get from the image in Figure to iviewer using the link in the Info tab (I see though that on the server which you list as an example (probably nightshade, and thus you are landing in the "old viewer when using that link in this case)
   - open the "birds eye view" on that image in iviewer
   - the red box in birds eye view is your ephemeral ROI, the birds eye view is your zoomed out image
   - you can now move around with the red box and see the "inset" in the main view

I do not suggest that this is a replacement of your workflow, rather wish to start a discussion to understand better your intended workflow.

Could you maybe add a motivation of your workflow to let us better understand the purpose ? Is it IDR motivated ? Public user viewing figures ?

**Comment by joshmoore** [comment]
This is the recent drawing that I was producing that I would have liked to have figure-ified:
![screen shot 2019-01-16 at 11 29 30](https://user-images.githubusercontent.com/88113/51243137-09a8a180-1982-11e9-8047-3a4ee9cee691.png)

So not particularly IDR-centric nor public data centric. Just "OMERO users wants to easily show insets" (or "zoom-levels" if you wish)

**Comment by pwalczysko** [comment]
Aha, thank you. Maybe the "interactivity" is not so crucial for your workflow then ? I was almost thinking about "magnifying glass" type workflow, but possibly this is not so crucial (although you probably want to adjust "a bit" after you have once drawn the ROI).
But I guess this is a false hope, you prbably need it all, including the connecting lines, because your images are large and zomplex and multi-z on top of that, so you cannot allow for too cumbersome jumping between dialogs.

So I guess you finally used the Copy and Paste in combination with the "zoom in" in the pasted panel and/or the "Crop" button in Figure to get the desired "insert" ?

**Comment by joshmoore** [comment]
> Maybe the "interactivity" is not so crucial for your workflow then ?

I think it is. This is _exactly_ what happened to me. Late in the process the choice of which tile to "inset" was changed.

> "magnifying glass" type workflow

I think this is a good way of thinking about it. I'm happy for this to be disconnected from "ROI" (though it may all be the same under the hood)

> And then added the lines in another software ?

Yes. It was all done in the end in Google Drawings.

**Comment by will-moore** [comment]
The linking-lines feature has been requested at https://forum.image.sc/t/omero-figure-improvements/72158
