### ISSUE TITLE
RFE: Histogram

### ISSUE THREAD

**Issue by dpwrussell** [ome/omero-figure#32]
Not strictly a Figure issue as everyone would love to see it in the clients as well, but it was mentioned so recording it here.

Basically everyone wants what softWoRx offers with regards to the histogram.

**Comment by pmcarlton** [comment]
I would like to chime in — for now instead of implementing copy/paste it would be nice to be able to just type in the values you want as an addition to the slider…it's difficult to select arbitrary values with the slider interface (as you are able to in softWoRx/Priism).

**Comment by feldman4** [comment]
+1 for editable sliders, especially useful when desired display range is much smaller than min/max pixel values

**Comment by will-moore** [comment]
@pmcarlton @feldman4 Just opened a PR allowing you to type in contrast values: #166

**Comment by will-moore** [comment]
Moved to trello card: https://trello.com/c/PcS5UkjS/133-histogram-support
