### ISSUE TITLE
rotate and crop errors

### ISSUE THREAD

**Issue by jburel** [ome/omero-figure#324]
From https://www.openmicroscopy.org/community/posting.php?mode=quote&f=4&p=20674
A user here at HMS reported to me that they were having problems with rotated and cropped figures. I was able to reproduce the problem. When you crop a figure that has been rotated the position of the cropping is not consistent with the output you get. The attached screenshot illustrates what is happening. The Preview pane shows what is intended. The resulting figure is offset to the lower left. The problem seems to be in the accuracy of the crop tool. If you reposition the crop frame only slightly, even though it appears to be in the wrong place, the correct crop is possible.

**Comment by will-moore** [comment]
Mapping from current crop region to Rectangle on rotated image is not taking account of rotation correctly (see screenshot)

![Screenshot 2020-12-15 at 13 13 08](https://user-images.githubusercontent.com/900055/102219531-8084a700-3ed7-11eb-8f27-9be42f23fcf8.png)

And the reverse mapping from crop Rectangle back to crop region on 'OK' also needs to take account of rotation.
