### ISSUE TITLE
Scalebar units should be selectable

### ISSUE THREAD

**Issue by hansduo** [ome/omero-figure#331]
This was already mentioned here a while ago (see: https://github.com/ome/omero-figure/issues/49 ): although µm may be the perfect choice for most usecases, the inability to choose different units unnecessarily excludes special types of images (e.g. EM, macroscopic, medical  or even telescopic images).

**Comment by will-moore** [comment]
Thanks for the feedback. We have a card for this at https://trello.com/c/R2mWNfR9/205-scale-bar-unit 
Regards, Will.

**Comment by will-moore** [comment]
This should be fixed when https://github.com/ome/omero-figure/pull/343 gets merged.
