### ISSUE TITLE
Handle >1k ROIs

### ISSUE THREAD

**Issue by joshmoore** [ome/omero-figure#334]
see https://forum.image.sc/t/omero-iviewer-cant-display-more-then-500-rois/27830

> I have images in OMERO with many ROIs. In the case of my specific example image its 1032 ROIs. When I open this image in OMERO-iviewer (0.6.0), only the first 500 ROIs are there. The same is true when opening the image in OMERO-figure (v4.0.2).

**Comment by will-moore** [comment]
As noted in that image.sc discussion, this is also an issue when loading Rectangles in the crop dialog.
