### ISSUE TITLE
Warn if save fails due to no permissions

### ISSUE THREAD

**Issue by manics** [ome/omero-figure#365]
## Public user
1. Open figure  as the public user
2. Create a new figure, add a public image
3. Click save. In the browser network console you'll see a 403 error but there's nothing in the UI to indicate it failed.

## Logged in user not in public group
1. Login as a user who is **not** a member of the public group
2. Browse the public group, since you should still be able to see it
3. Open figure
4. Create a new figure, add a public image
5. Click save. In the browser network console you'll see a 500 error but there's nothing in the UI to indicate it failed.

The latter is arguably a bigger problem. There is no expectation of the public user being able to save, however a user who is logged in but in the wrong group might still expect the save to work.

**Comment by will-moore** [comment]
The latter scenario shouldn't be possible. If you are logged-in as a user who is not a member of the public group, you won't be able to access images that are in the public group.

**Comment by will-moore** [comment]
The first scenario should be fixed by #415
