### ISSUE TITLE
Silent error when image is bigger than page size

### ISSUE THREAD

**Issue by Trefex** [ome/omero-figure#37]
Hi,

While fiddling with the allowed image size, we noticed that if the image is very big, the panel which holds the image in the figure gets created but not populated. The image successfully loads in the Preview, but not in the figure view.

Looking at the console, there are some JS errors coming from raphael.js having to do with negative coordinates on x-y system.

This bug is in principle not an issue when the pixel size is restricted to 5000x5000 but if this setting was arbitrary, there might still be a bug to be fixed here.

**Comment by Trefex** [comment]
Any updates on this?

**Comment by will-moore** [comment]
Sorry, no. I'll look at it for a 1.1.1 release which will be needed quite soon.

**Comment by Trefex** [comment]
:+1:

**Comment by will-moore** [comment]
@Trefex: I found one potential fix for this (see https://github.com/will-moore/figure/pull/81) but if you could give me some example image sizes and paper sizes then I can test that I've fixed the same error you're seeing.

**Comment by Trefex** [comment]
Hi @will-moore , one image where it fails is 8286 x 4415. It just shows an empty square instead of the image.

**Comment by will-moore** [comment]
OK, seems to be working for images of that size now....

**Comment by Trefex** [comment]
:+1:
