### ISSUE TITLE
Scale bar cannot be less than 1 um.

### ISSUE THREAD

**Issue by iandobbie** [ome/omero-figure#373]
I have an image with pixel sizes defined in um and I am  unable to set the scale bar to less than  1 um which would be nicer on some image where the region is highly magnified.

**Comment by iandobbie** [comment]
I now see that there appears to be a modification in the last couple of weeks which might address this. I will test this and see if it solves my issuse.

**Comment by will-moore** [comment]
Hi, hopefully https://github.com/ome/omero-figure/pull/343 will address this issue.
Let us know if not.
