### ISSUE TITLE
slider, knobs layout preview tab

### ISSUE THREAD

**Issue by jburel** [ome/omero-figure#397]
sliders' knobs are now nicely in the middle of the track
also the z-slider and arrows are not aligned
Checked on firefox and chrome
<img width="366" alt="Screenshot 2020-08-03 at 11 51 51" src="https://user-images.githubusercontent.com/1022396/89175492-cb80cc00-d57f-11ea-9742-a2cecbdb6c1c.png">

**Comment by jburel** [comment]
vs iviewer slider
<img width="367" alt="Screenshot 2020-08-03 at 11 52 57" src="https://user-images.githubusercontent.com/1022396/89175579-ea7f5e00-d57f-11ea-9315-cd3de6fb1dc1.png">

**Comment by will-moore** [comment]
This looks like it might be due to jQuery and jQuery-UI upgrade in https://github.com/ome/omero-web/pull/180

**Comment by will-moore** [comment]
Should be fixed by https://github.com/ome/omero-web/pull/180/commits/1d9c45b57ce63a252c349f3042196b2ee95b5d48
