### ISSUE TITLE
ROI rectangle inset rotation

### ISSUE THREAD

**Issue by will-moore** [ome/omero-figure#408]
See https://forum.image.sc/t/omero-figure-box-annotations-rotated-incorrectly/45787

Copy the crop region from a rotated image and paste on it's "parent" image - but the new Rectangle isn't rotated.

Just playing with css tools, a fix can be simulated with a transform of negative rotation and transform-origin. See:

![Screenshot 2020-11-26 at 10 27 43](https://user-images.githubusercontent.com/900055/100340354-f382b800-2fd2-11eb-99cd-0d401673445c.png)

But, we'd need to save this and handle it somehow when Editing the rectangle?

**Comment by will-moore** [comment]
One solution might be to create a Polygon when user pastes a Rotated crop region.
This would solve the display of it in the Edit tab and it wouldn't be editable.
It would also export correctly without any change in the export script.

**Comment by pwalczysko** [comment]
Works as expected. Tested the described workflow as well as drawing a normal rectangle and rotating the same panel.
Both worked.
