### ISSUE TITLE
Fractional LUT range entries for float pixel values

### ISSUE THREAD

**Issue by drjrkuhn** [ome/omero-figure#467]
For images with floating point pixel values, the iviewer allows one to enter fractional values for LUT min and max. Sometimes those ranges are small fractions. For example, MMP12 (Magenta) in this screenshot ranges from 0 to 0.6.

![Screen Shot 2022-06-03 at 3 21 40 PM](https://user-images.githubusercontent.com/5713226/171935566-7862b70a-5b62-4e6d-91f8-94852bc03529.png)

The Omero figure interface does not properly check for floating point pixel values. Min and max accept only integer values (no decimal point). For small fractional values, the LUT display range in OMERO-figure is unable to cope.

![Screen Shot 2022-06-03 at 3 21 20 PM](https://user-images.githubusercontent.com/5713226/171935576-aba92f66-e29f-415b-864c-7e94d439d809.png)

This image was taken with an Akoya PhenoImager. Their spectral unmixing produces float pixels.

**Comment by will-moore** [comment]
Looking at the iviewer code, I was expecting to see that the 'steps' (increments) of the slider to be dynamic, depending on the range. But actually it looks like the step is fixed at `0.01`.

https://github.com/ome/omero-iviewer/blob/f98323a4bf24e3474537bd79195283e909dac78c/src/controls/dimension-slider.js#L293

I notice from your screenshot that only the "untouched" sliders where the value are at min/max have an increment that is smaller than `0.01`.
However, if this works for you then that is an easy change to apply to OMERO.figure.

**Comment by will-moore** [comment]
This fix is in the latest v5.0.0 release of OMERO.figure.
