### ISSUE TITLE
Rotate 90° without cropping

### ISSUE THREAD

**Issue by will-moore** [ome/omero-figure#484]
See https://forum.image.sc/t/couple-of-suggestions-about-omero-figure/72675

"In the preview tab, for rectangle images, rotating the image crops a part of it because of the fix canvas. Therefore, it is not possible to flip the image by 90° and having it entirely displayed. I think it could be great to have an option to flip the image by 90° and 180° (left and right)."

This feature exists on various photo apps, often with a single button that rotates the image by 90° each time it's clicked, with icons like:

![Screenshot 2022-10-13 at 09 46 37](https://user-images.githubusercontent.com/900055/195549688-97441e0d-edf4-48b7-bc67-3039b20fa93f.png)
![Screenshot 2022-10-13 at 09 48 20](https://user-images.githubusercontent.com/900055/195549718-7361dd5e-cc24-4ab5-95ba-d16e76e0c991.png)

OMERO.figure could do this by automatically setting the rotation value and updating the width/height at the same time.

**Comment by Rdornier** [comment]
There is a issue when rotating and cropping an image. The cropped image loose the rotation information of the parent image
