### ISSUE TITLE
confine Z-projections

### ISSUE THREAD

**Issue by will-moore** [ome/omero-figure#546]
webclient (https://github.com/ome/omero-web/pull/115) and iviewer (https://github.com/ome/omero-iviewer/pull/305) restrict the amount of data you can use in max-intensity projection by disabling Z-projection for images over `256 * 1024 * 1024` bytes (ignoring sizeT).

E.g.
https://github.com/ome/omero-web/blob/4d8d25ef7528e49cadfb5b777a47f6953c198fba/omeroweb/webgateway/templates/webgateway/viewport/omero_image.html#L1123

This has been made a server-side config values:
https://github.com/ome/omero-common/pull/22
https://github.com/ome/omero-model/pull/47
but not implemented in webclient or iviewer yet.

cc @chris-allan

**Comment by sbesson** [comment]
Is this a duplicate of https://github.com/ome/omero-figure/issues/440 ?

**Comment by will-moore** [comment]
@sbesson Yes, thanks - I missed that one. I'll close this one and update that one!
