### ISSUE TITLE
Can't enable figure export

### ISSUE THREAD

**Issue by jo-mueller** [ome/omero-figure#565]
Dear OMERO-figure team,

I was recently playing with OMERO figure a bit and I am super impressed with the features. I was then trying to enable the export as described in the [docs here](https://pypi.org/project/omero-figure/) but couldn't get it to work. Here is how I tried to set it up:

1. OMERO is running inside a docker container - I am logging into this container using `docker exec -it <ID> bash`
2. I installed omero-figure using `pip install -U omero-figure`
3. I navigated to the directory indicated by `pip show omero-figure`:

```bash
bash-5.1$ pip show omero-figure
Name: omero-figure
Version: 6.2.2
Summary: OMERO figure creation app
Home-page: https://github.com/ome/omero-figure
Author: The Open Microscopy Team
Author-email: ome-devel@lists.openmicroscopy.org.uk
License: AGPL-3.0
Location: /opt/omero/server/.local/lib/python3.9/site-packages
Requires: omero-web
Required-by:
```

4. I navigated to the location: `cd /opt/omero/server/.local/lib/python3.9/site-packages`
5. I navigated to the scripts directory: `cd omero_figure/scripts`
6. Tried to upload the script with `omero script upload omero/figure_scripts/Figure_To_Pdf.py --official` and received this error:
```
bash-5.1$ omero
bash: omero: command not found
```

which indicates that the `omero` command is somehow not available to the default `omero-server` user. I tried to log in as `root`, but I don't know the default `root` password. I use the setup from [this repo](https://github.com/ome/docker-example-omero) as starting point, where a `ROOTPASS` variable is set, but I can't log in with it. But I'm not sure that this is a docker issue.

Anyway, some directions on how to fix would be really helpful - I would be happy to add a short note to the docs in a PR if something new is to be learned from this :)

Best, Johannes

**Comment by jo-mueller** [comment]
@will-moore thanks for the help, worked like a charm. Would you mind if I sent a PR with a short note as *Option 3* for the docs of omero-figure?

**Comment by will-moore** [comment]
Please do, thanks!
