### ISSUE TITLE
sortable.js cannot be resolved

### ISSUE THREAD

**Issue by Rdornier** [ome/omero-figure#582]
Hi,

I have an  issue running omero.figure with the latest available commit  430fc3f. It seems that `Sortable` is not found.

![image](https://github.com/user-attachments/assets/9030817d-7223-4be1-bc25-57c189bd1f8a)

Is it something I need to configure in my dev env ? I also noticed that `package.json` have been modified with the `sortable.js` dependency but not `package-lock.json`. 

Thanks,
Rémy.

**Comment by will-moore** [comment]
You probably just need to do `npm install`.

**Comment by Rdornier** [comment]
Thanks, it works again !
