### ISSUE TITLE
Change background color of canvas

### ISSUE THREAD

**Issue by Trefex** [ome/omero-figure#80]
Will,

It would be great if we could use the current color wheel to set the background color of the Canvas.

Indeed, sometimes it is preferable to have a black background for instance instead of white.

What say you?

**Comment by will-moore** [comment]
Hmmm - I never thought anyone would want a different colour background, but it should be possible.

**Comment by Trefex** [comment]
True, however some people sometimes do black slides and so they want to have black backgrounds. It's a minor request though

**Comment by will-moore** [comment]
Also requested at https://trello.com/c/55EzQq2e/135-set-page-colour
Closing issue...
