### ISSUE TITLE
RFE: Pixel size on crop tool

### ISSUE THREAD

**Issue by gusferguson** [ome/omero-figure#84]
From Sandra:
Needs the pixel size for the selection frame when cropping 
Wants to be able to see the size and whether square etc. when cropping an image so can do same size-shaped crop on another image to enable comparison.

**Comment by will-moore** [comment]
Thanks, this is already a trello card at https://trello.com/c/Lo3XQjmx/90-show-x-y-w-h-for-selected-region-in-crop-dialog

**Comment by will-moore** [comment]
NB: you can restrain the ROI to be square by holding down Shift key while drawing / resizing crop region.

**Comment by will-moore** [comment]
Follow trello card - closing issue....
