### ISSUE TITLE
automatically add tags as panel labels

### ISSUE THREAD

**Issue by feldman4** [ome/omero-figure#86]
Is there a plan in the works to have tags available in the same way [channels] etc are currently? I think it would be useful for fast consistent annotation.

**Comment by will-moore** [comment]
Yes, this has been requested by other users and is certainly on my TODO list.
Thanks for your feedback.

**Comment by will-moore** [comment]
Created trello card. https://trello.com/c/ZdmnimZj/64-labels-from-tags
Closing issue...
